"use strict";
let decimal = 10;
let hex = 0xf00d;
let binary = 0b1010;
let octal = 0o744;
let notANumber = NaN;
let underscoreNum = 1000000;
console.log(typeof decimal);
console.log(typeof hex);
console.log(typeof binary);
console.log(typeof octal);
console.log(typeof notANumber);
console.log(typeof underscoreNum);
